apiVersion: v1
name: efk
version: 0.0.1
appVersion: 7.4.0
dependencies:
- name: elasticsearch
  repository: file://.charts/elasticsearch
  version: 7.4.0
- name: fluent-bit
  repository: file://.charts/fluent-bit
  version: 0.2.11
- name: kibana
  repository: file://.charts/kibana
  version: 7.4.0
keywords:
- elasticsearch
- kibana
- fluent-bit
description: EFK stack
